# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5570409713dd4f314af9d9830a37f76c7bc212d6da38febc49df780aa2941d2ec983787f1ceb8269b208a5fd6b55435f561703503303bd03eb5d24193e004c21

test:
  secret_key_base: dab92467a779bf0707ee20e1c0a716e4cec14e56c6c3f201c3ffdd51afe2b403e419740903a100b96eb27870ddaf3bd99ad6d3704bd9b421c06e7db82b795099

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
