recaptcha:
  public_key: 
  private_key: 

mail:
  user_name: 
  password: 

session:
  key: 
  secret: 
          
twitter:
  consumer_key: 
  consumer_secret: 
  oauth_token: 
  oauth_token_secret: 